//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorldMVCApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_employee
    {
        [Required]
        [DataType("System.Int32")]
        public int ecode { get; set; }
        [Required]
        [DataType("System.String")]
        [RegularExpression("[aA-zZ]*",ErrorMessage ="Invalid Employee name! Name must only contain characters")]
        public string ename { get; set; }
        [Required]
        [Range(20000,50000)]
        public Nullable<int> salary { get; set; }
        [Required]
        public Nullable<int> deptid { get; set; }
    }
}
